var annotated =
[
    [ "CalDavFactory", "namespaceCalDavFactory.html", "namespaceCalDavFactory" ],
    [ "CardDAVFactory", "namespaceCardDAVFactory.html", "namespaceCardDAVFactory" ],
    [ "EDSCalendarFactory", "namespaceEDSCalendarFactory.html", "namespaceEDSCalendarFactory" ],
    [ "EDSContactsFactory", "namespaceEDSContactsFactory.html", "namespaceEDSContactsFactory" ],
    [ "OpenAB", "namespaceOpenAB.html", "namespaceOpenAB" ],
    [ "OpenAB_Plugin", "namespaceOpenAB__Plugin.html", "namespaceOpenAB__Plugin" ],
    [ "OpenAB_Source", "namespaceOpenAB__Source.html", "namespaceOpenAB__Source" ],
    [ "OpenAB_Storage", "namespaceOpenAB__Storage.html", "namespaceOpenAB__Storage" ],
    [ "OpenAB_Sync", "namespaceOpenAB__Sync.html", "namespaceOpenAB__Sync" ],
    [ "_GDataOAuth2AuthorizerPrivate", "struct__GDataOAuth2AuthorizerPrivate.html", "struct__GDataOAuth2AuthorizerPrivate" ],
    [ "_OAuth2SecureString", "struct__OAuth2SecureString.html", "struct__OAuth2SecureString" ],
    [ "BluezOBEXTransfer", "classBluezOBEXTransfer.html", "classBluezOBEXTransfer" ],
    [ "CalDAVHelper", "classCalDAVHelper.html", "classCalDAVHelper" ],
    [ "CalDAVStorage", "classCalDAVStorage.html", "classCalDAVStorage" ],
    [ "CalDAVStorageItemIterator", "classCalDAVStorageItemIterator.html", "classCalDAVStorageItemIterator" ],
    [ "CardDAVHelper", "classCardDAVHelper.html", "classCardDAVHelper" ],
    [ "CardDAVStorage", "classCardDAVStorage.html", "classCardDAVStorage" ],
    [ "CardDAVStorageItemIterator", "classCardDAVStorageItemIterator.html", "classCardDAVStorageItemIterator" ],
    [ "DAVHelper", "classDAVHelper.html", "classDAVHelper" ],
    [ "EDSCalendarStorage", "classEDSCalendarStorage.html", "classEDSCalendarStorage" ],
    [ "EDSCalendarStorageCommon", "classEDSCalendarStorageCommon.html", null ],
    [ "EDSCalendarStorageItemIterator", "classEDSCalendarStorageItemIterator.html", "classEDSCalendarStorageItemIterator" ],
    [ "EDSContactsStorage", "classEDSContactsStorage.html", "classEDSContactsStorage" ],
    [ "EDSContactsStorageItemIterator", "classEDSContactsStorageItemIterator.html", "classEDSContactsStorageItemIterator" ],
    [ "FIFOBuffer", "classFIFOBuffer.html", "classFIFOBuffer" ],
    [ "FileSource", "classFileSource.html", "classFileSource" ],
    [ "GDataContactsConverter", "classGDataContactsConverter.html", "classGDataContactsConverter" ],
    [ "GDataOAuth2Authorizer", "structGDataOAuth2Authorizer.html", "structGDataOAuth2Authorizer" ],
    [ "GDataOAuth2AuthorizerClass", "structGDataOAuth2AuthorizerClass.html", "structGDataOAuth2AuthorizerClass" ],
    [ "GoogleSource", "classGoogleSource.html", "classGoogleSource" ],
    [ "OneWaySync", "classOneWaySync.html", "classOneWaySync" ],
    [ "OpenAB_Sync_params", "structOpenAB__Sync__params.html", "structOpenAB__Sync__params" ],
    [ "PBAPSource", "classPBAPSource.html", "classPBAPSource" ],
    [ "TwoWaySync", "classTwoWaySync.html", "classTwoWaySync" ]
];