var namespaceOpenAB =
[
    [ "BasicHttpAuthorizer", "classOpenAB_1_1BasicHttpAuthorizer.html", "classOpenAB_1_1BasicHttpAuthorizer" ],
    [ "DefaultLogger", "classOpenAB_1_1DefaultLogger.html", "classOpenAB_1_1DefaultLogger" ],
    [ "HttpAuthorizer", "classOpenAB_1_1HttpAuthorizer.html", "classOpenAB_1_1HttpAuthorizer" ],
    [ "HttpMessage", "classOpenAB_1_1HttpMessage.html", "classOpenAB_1_1HttpMessage" ],
    [ "HttpSession", "classOpenAB_1_1HttpSession.html", "classOpenAB_1_1HttpSession" ],
    [ "ItemField", "classOpenAB_1_1ItemField.html", "classOpenAB_1_1ItemField" ],
    [ "KeyValueItem", "classOpenAB_1_1KeyValueItem.html", "classOpenAB_1_1KeyValueItem" ],
    [ "KeyValueItemFactory", "classOpenAB_1_1KeyValueItemFactory.html", "classOpenAB_1_1KeyValueItemFactory" ],
    [ "Logger", "classOpenAB_1_1Logger.html", "classOpenAB_1_1Logger" ],
    [ "OAuth2HttpAuthorizer", "classOpenAB_1_1OAuth2HttpAuthorizer.html", "classOpenAB_1_1OAuth2HttpAuthorizer" ],
    [ "PIMCalendarEventItem", "classOpenAB_1_1PIMCalendarEventItem.html", "classOpenAB_1_1PIMCalendarEventItem" ],
    [ "PIMCalendarEventItemIndex", "classOpenAB_1_1PIMCalendarEventItemIndex.html", "classOpenAB_1_1PIMCalendarEventItemIndex" ],
    [ "PIMCalendarItem", "classOpenAB_1_1PIMCalendarItem.html", "classOpenAB_1_1PIMCalendarItem" ],
    [ "PIMCalendarItemIndex", "classOpenAB_1_1PIMCalendarItemIndex.html", "classOpenAB_1_1PIMCalendarItemIndex" ],
    [ "PIMCalendarTaskItem", "classOpenAB_1_1PIMCalendarTaskItem.html", "classOpenAB_1_1PIMCalendarTaskItem" ],
    [ "PIMCalendarTaskItemIndex", "classOpenAB_1_1PIMCalendarTaskItemIndex.html", "classOpenAB_1_1PIMCalendarTaskItemIndex" ],
    [ "PIMContactItem", "classOpenAB_1_1PIMContactItem.html", "classOpenAB_1_1PIMContactItem" ],
    [ "PIMContactItemIndex", "classOpenAB_1_1PIMContactItemIndex.html", "classOpenAB_1_1PIMContactItemIndex" ],
    [ "PIMItem", "classOpenAB_1_1PIMItem.html", "classOpenAB_1_1PIMItem" ],
    [ "PIMItemIndex", "classOpenAB_1_1PIMItemIndex.html", "classOpenAB_1_1PIMItemIndex" ],
    [ "PluginManager", "classOpenAB_1_1PluginManager.html", "classOpenAB_1_1PluginManager" ],
    [ "SecureString", "classOpenAB_1_1SecureString.html", "classOpenAB_1_1SecureString" ],
    [ "SmartPtr", "classOpenAB_1_1SmartPtr.html", "classOpenAB_1_1SmartPtr" ],
    [ "TimeStamp", "classOpenAB_1_1TimeStamp.html", "classOpenAB_1_1TimeStamp" ],
    [ "Variant", "classOpenAB_1_1Variant.html", "classOpenAB_1_1Variant" ],
    [ "VCardField", "classOpenAB_1_1VCardField.html", "classOpenAB_1_1VCardField" ],
    [ "VCardPhoto", "classOpenAB_1_1VCardPhoto.html", null ],
    [ "VDayLightTimeZoneKeyValueItem", "classOpenAB_1_1VDayLightTimeZoneKeyValueItem.html", "classOpenAB_1_1VDayLightTimeZoneKeyValueItem" ],
    [ "VStandardTimeZoneKeyValueItem", "classOpenAB_1_1VStandardTimeZoneKeyValueItem.html", "classOpenAB_1_1VStandardTimeZoneKeyValueItem" ]
];